title: JOKER Project 2025
description: CLEF 2025 JOKER Track - Automatic Humour Analysis

theme: null
remote_theme: daviddarnes/alembic@main

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Configuration automatique du menu d'Alembic
navigation:
  - title: Accueil
    url: /
  - title: Première Page
    url: /First_page/
  - title: Contact
    url: /contact/
